# Generated by Django 2.2.9 on 2020-01-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='작성일', null=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='일기 이미지', null=True, upload_to='images', verbose_name='일기 이미지'),
        ),
    ]
